### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by gautam1858** [stanfordnmbl/osim-rl#121]
I am getting the following error, please help me with this 

`ERROR: test_activations (__main__.ActivationsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.activations.py", line 12, in test_activations
    env.osim_model.set_activations(newact)
  File "/Users/neutrino/anaconda3/envs/orl/lib/python3.6/site-packages/osim/env/osim.py", line 113, in set_activations
    self.muscleSet.get(j).setActivation(self.state, activations[j])
IndexError: index 18 is out of bounds for axis 0 with size 18

======================================================================
ERROR: test_activations_changes (__main__.ActivationsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.activations.py", line 31, in test_activations_changes
    env.osim_model.set_activations(newAct)
  File "/Users/neutrino/anaconda3/envs/orl/lib/python3.6/site-packages/osim/env/osim.py", line 113, in set_activations
    self.muscleSet.get(j).setActivation(self.state, activations[j])
IndexError: list index out of range

----------------------------------------------------------------------
Ran 2 tests in 0.151s

FAILED (errors=2)`

**Comment by kidzik** [comment]
@gautam1858 you are using a model with less 18 muscles, while `ActivationsTest` has hardcoded 18 muscles. Please be superprecise with the actual setting and the code and someone will definitely help you with your issue.

**Comment by gautam1858** [comment]
@kidzik oh yeah I changed the number of muscles and now it seems to work
