### ISSUE TITLE
Errors on a vanilla Ubuntu 16.04 install

### ISSUE THREAD

**Issue by spMohanty** [stanfordnmbl/osim-rl#14]
I ran into this on a vanilla Ubuntu 16.04 install after setting up everything through conda.
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/anaconda2/envs/opensim-rl/lib/python2.7/site-packages/opensim/__init__.py", line 1, in <module>
    from simbody import *
  File "/home/ubuntu/anaconda2/envs/opensim-rl/lib/python2.7/site-packages/opensim/simbody.py", line 28, in <module>
    _simbody = swig_import_helper()
  File "/home/ubuntu/anaconda2/envs/opensim-rl/lib/python2.7/site-packages/opensim/simbody.py", line 24, in swig_import_helper
    _mod = imp.load_module('_simbody', fp, pathname, description)
ImportError: libquadmath.so.0: cannot open shared object file: No such file or directory
```

Can be fixed by :
```
sudo apt-get install libquadmath0
```

**Comment by spMohanty** [comment]
There was also this :
```
simbody-visualizer: error while loading shared libraries: libGLU.so.1: cannot open shared object file: No such file or directory

```

Can be fixed by :
```
sudo apt-get install libglu1-mesa libglu1-mesa-dev
```

**Comment by kidzik** [comment]
Thanks for the update, I will try to add it to conda environment if possible, otherwise, I will put it in README

**Comment by kidzik** [comment]
On this low level (GLUT etc.) it might be fine to just install things system-wide, so I add the `apt` packages to the README. Thanks for spotting this.
