### ISSUE TITLE
Submission Error

### ISSUE THREAD

**Issue by joneswong** [stanfordnmbl/osim-rl#171]
I encountered the same issue as this thread discussed: https://www.crowdai.org/topics/submit-fail-connection-reset-by-peer/discussion

Traceback (most recent call last):
  File "/gruntdata/app_data/jones.wz/anaconda2/envs/opensim-rl/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/gruntdata/app_data/jones.wz/anaconda2/envs/opensim-rl/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/gruntdata/app_data/jones.wz/anaconda2/envs/opensim-rl/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/gruntdata/app_data/jones.wz/anaconda2/envs/opensim-rl/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/gruntdata/app_data/jones.wz/anaconda2/envs/opensim-rl/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/gruntdata/app_data/jones.wz/anaconda2/envs/opensim-rl/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/gruntdata/app_data/jones.wz/anaconda2/envs/opensim-rl/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

This error always happens after:
 
POST http://grader.crowdai.org:1729/v1/envs/8078___78cb73746b/step/
{"action": [1.0, 0.0, 1.0, 0.0, 1.0, 0.11727721244096756, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], "render": true}

**Comment by kidzik** [comment]
@spMohanty are there any updates on this one?
@joneswong indeed we encountered this before -- at the very least your solution will be scored after submitting the docker container (this is how we will score the top solutions at the end)

**Comment by spMohanty** [comment]
@kidzik : I havent yet been able to properly replicate this unfortunately :/

**Comment by kidzik** [comment]
That's ok, I think we won't be able to fix it by the end of the challenge, unfortunately, but since the final grading is based on docker submissions it will still be fair.
