### ISSUE TITLE
submit.py || Connection error

### ISSUE THREAD

**Issue by ishgirwan** [stanfordnmbl/osim-rl#19]
Hi,

I am getting connection error while trying to execute `submit.py`.

Traceback (most recent call last):
```
File "submit.py", line 19, in
observation = client.env_create(args.token)
File "/Users/Ish/anaconda/envs/opensim-rl/lib/python2.7/site-packages/osim/http/client.py", line 52, in env_create
resp = self._post_request(route, data)
File "/Users/Ish/anaconda/envs/opensim-rl/lib/python2.7/site-packages/osim/http/client.py", line 39, in _post_request
data=json.dumps(data))
File "/Users/Ish/anaconda/envs/opensim-rl/lib/python2.7/site-packages/requests/sessions.py", line 549, in post
return self.request('POST', url, data=data, json=json, **kwargs)
File "/Users/Ish/anaconda/envs/opensim-rl/lib/python2.7/site-packages/requests/sessions.py", line 502, in request
resp = self.send(prep, **send_kwargs)
File "/Users/Ish/anaconda/envs/opensim-rl/lib/python2.7/site-packages/requests/sessions.py", line 612, in send
r = adapter.send(request, **kwargs)
File "/Users/Ish/anaconda/envs/opensim-rl/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

**Comment by kidzik** [comment]
Thanks, we will investigate it promptly! There seems to be an error with the grader on the server.

**Comment by kidzik** [comment]
Hi, actually just on the launch of the challenge we changed the port of the grader server, sorry for that. Please try the updated environment or just set
```python
remote_base = "http://grader.crowdai.org:1729"
```
