### ISSUE TITLE
Exception in the grader

### ISSUE THREAD

**Issue by spMohanty** [stanfordnmbl/osim-rl#20]
```
[2017-06-22 02:49:16,055] Exception on /v1/envs/ [POST]
Traceback (most recent call last):
  File "/home/ubuntu/anaconda2/envs/opensim-rl/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/anaconda2/envs/opensim-rl/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/anaconda2/envs/opensim-rl/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/anaconda2/envs/opensim-rl/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/anaconda2/envs/opensim-rl/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "gym_http_server.py", line 324, in env_create
    instance_id = envs.create(env_id, token)
  File "gym_http_server.py", line 110, in create
    env = osim_envs[env_id](visualize=False)
  File "/home/ubuntu/SDF/osim-rl/osim/env/run.py", line 30, in __init__
    super(RunEnv, self).__init__(visualize = False, noutput = self.noutput)
  File "/home/ubuntu/SDF/osim-rl/osim/env/osim.py", line 114, in __init__
    self.osim_model = Osim(self.model_path, self.visualize)
  File "/home/ubuntu/SDF/osim-rl/osim/env/osim.py", line 36, in __init__
    self.brain.addActuator(self.muscleSet.get(j))
  File "/home/ubuntu/anaconda2/envs/opensim-rl/lib/python2.7/site-packages/opensim/simulation.py", line 25876, in addActuator
    return _simulation.Controller_addActuator(self, actuator)
RuntimeError: std::exception in 'void OpenSim::Controller::addActuator(OpenSim::Actuator const &)': PropertyTable::updAbstractPropertyByIndex(): index 0 out of range (0 properties in table).
```

I have been seeing this a lot lately in the grader error logs.
Any clue about the source of the error ?

**Comment by kidzik** [comment]
Do you know anything more about when it is happening? During every submission? Does the submission fail?
On the first sight, it seems suspicious that it reads opensim from anaconda but osim-rl from some other directory.

**Comment by spMohanty** [comment]
The `osim-rl` is being read from a different directory because I installed it using `pip install -e` to let me quickly try out patches.
But it seems to be an exception inside OpenSim.

I had not updated the opensim-rl conda package. Might be because of that. I just updated it, and will keep an eye on the logs of the grader.

**Comment by chrisdembia** [comment]
@spMohanty what platform is this on?

**Comment by chrisdembia** [comment]
@spMohanty would you be able to help with providing a minimum working example that shows this bug?

**Comment by kidzik** [comment]
@spMohanty is this still not working?

**Comment by spMohanty** [comment]
@kidzik : Yeah its more stable now. Though occassionally I do see this error in the logs. But havent seen a lot of it after setting up everything in a completely new environment.

**Comment by kidzik** [comment]
Sounds good, I am closing this one for now, please reopen if you see any pattern. In principle it should have been solved with this commit a while ago https://github.com/stanfordnmbl/osim-rl/commit/21cc8adb3e77e969f209d8e4405320885e71c5f3
