### ISSUE TITLE
error when running example.py --visualize --train

### ISSUE THREAD

**Issue by seandevs** [stanfordnmbl/osim-rl#22]
When following directions in **Training Your First Model** and running python 2.7.13 (conda 4.3.22), I get the following error. Please let me know any further info that I can provide.

```
Training for 10000 steps ...
Traceback (most recent call last):
  File "example.py", line 86, in <module>
    agent.fit(env, nb_steps=nallsteps, visualize=False, verbose=1, nb_max_episode_steps=env.timestep_limit, log_interval=10000)
  File "/Users/me/anaconda3/envs/opensim-rl/lib/python2.7/site-packages/rl/core.py", line 70, in fit
    observation = deepcopy(env.reset())
  File "/Users/me/anaconda3/envs/opensim-rl/lib/python2.7/site-packages/osim/env/run.py", line 53, in reset
    super(RunEnv, self).reset()
  File "/Users/me/anaconda3/envs/opensim-rl/lib/python2.7/site-packages/gym/core.py", line 104, in reset
    return self._reset()
  File "/Users/me/anaconda3/envs/opensim-rl/lib/python2.7/site-packages/osim/env/osim.py", line 146, in _reset
    return self.get_observation()
  File "/Users/me/anaconda3/envs/opensim-rl/lib/python2.7/site-packages/osim/env/run.py", line 133, in get_observation
    obstacle = self.next_obstacle()
  File "/Users/me/anaconda3/envs/opensim-rl/lib/python2.7/site-packages/osim/env/run.py", line 111, in next_obstacle
    return map(lambda xy: xy[0]-xy[1], [x for x in zip(obstacle, [xy[0],0,0])])
NameError: global name 'xy' is not defined
```

**Comment by kidzik** [comment]
Can you please try to update the osim environment with 

    pip install git+https://github.com/stanfordnmbl/osim-rl.git -U 

Thanks!

**Comment by seandevs** [comment]
absolutely - getting this now

```
Traceback (most recent call last):
  File "example.py", line 86, in <module>
    agent.fit(env, nb_steps=nallsteps, visualize=False, verbose=1, nb_max_episode_steps=env.timestep_limit, log_interval=10000)
  File "/Users/me/anaconda3/envs/opensim-rl/lib/python2.7/site-packages/rl/core.py", line 107, in fit
    action = self.forward(observation)
  File "/Users/me/anaconda3/envs/opensim-rl/lib/python2.7/site-packages/rl/agents/ddpg.py", line 230, in forward
    action = self.select_action(state)  # TODO: move this into policy
  File "/Users/me/anaconda3/envs/opensim-rl/lib/python2.7/site-packages/rl/agents/ddpg.py", line 216, in select_action
    action = self.actor.predict_on_batch(batch).flatten()
  File "/Users/me/anaconda3/envs/opensim-rl/lib/python2.7/site-packages/keras/models.py", line 905, in predict_on_batch
    return self.model.predict_on_batch(x)
  File "/Users/me/anaconda3/envs/opensim-rl/lib/python2.7/site-packages/keras/engine/training.py", line 1677, in predict_on_batch
    self._feed_input_shapes)
  File "/Users/me/anaconda3/envs/opensim-rl/lib/python2.7/site-packages/keras/engine/training.py", line 133, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking : expected flatten_1_input to have shape (None, 1, 41) but got array with shape (1, 1, 34)
```

**Comment by kidzik** [comment]
My quick hack for making python3 work turned out to be buggy in python2, sorry about that. Please try updating the osim environment again

    pip install git+https://github.com/stanfordnmbl/osim-rl.git -U 

Thanks!

**Comment by seandevs** [comment]
No issues! I saw there was a push just an hour before my pull so assumed something similar. Thanks so much for the quick fix! Its working perfectly.

**Comment by kidzik** [comment]
I've noticed I left a `print` there dumping some values, now the updated version should finally be good (I tried fixing to quickly). Thanks for your help! Time to write proper tests finally :)
