### ISSUE TITLE
ModuleNotFoundError: No module named '_simbody'

### ISSUE THREAD

**Issue by NicolasGrandin** [stanfordnmbl/osim-rl#233]
Hello everyone ! 

I am new to python and opensim, so... ,sorry if my questions are "simple".

I'am currently using OpenSim 4.2. (64 bit) and  Python 3.7.10 (64 bit).

When I try to import the opensim package into Python I have this error message : 

import opensim
Traceback (most recent call last):

  File "D:\Anaconda3\envs\OpenSim\lib\site-packages\opensim-4.2_2021_03_12_fcedec9-py3.7.egg\opensim\simbody.py", line 14, in swig_import_helper
    return importlib.import_module(mname)

  File "D:\Anaconda3\envs\OpenSim\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import

  File "<frozen importlib._bootstrap>", line 983, in _find_and_load

  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked

  File "<frozen importlib._bootstrap>", line 583, in module_from_spec

  File "<frozen importlib._bootstrap_external>", line 1043, in create_module

  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

ImportError: DLL load failed: Le module spécifié est introuvable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-1-d100d6ac66f2>", line 1, in <module>
    import opensim

  File "D:\Anaconda3\envs\OpenSim\lib\site-packages\opensim-4.2_2021_03_12_fcedec9-py3.7.egg\opensim\__init__.py", line 1, in <module>
    from .simbody import *

  File "D:\Anaconda3\envs\OpenSim\lib\site-packages\opensim-4.2_2021_03_12_fcedec9-py3.7.egg\opensim\simbody.py", line 17, in <module>
    _simbody = swig_import_helper()

  File "D:\Anaconda3\envs\OpenSim\lib\site-packages\opensim-4.2_2021_03_12_fcedec9-py3.7.egg\opensim\simbody.py", line 16, in swig_import_helper
    return importlib.import_module('_simbody')

  File "D:\Anaconda3\envs\OpenSim\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

ModuleNotFoundError: No module named '_simbody'

**Comment by oskarasbrink** [comment]
having a very similar error with python 3.6.1. Did you fix this?

**Comment by NicolasGrandin** [comment]
Hi @oskarasbrink ,

I just managed this by changing the installation folder name (frome OpenSim 4.2 to Opensim4.2)  and then by installing twice the python setup... Weird but it worked

**Comment by qmadorell** [comment]
Did it work for both of you? I haven't managed to fix it, I'm working with my mac.

**Comment by NicolasGrandin** [comment]
I tried with 2 different computers (both windows) and it worked.
You may have a problem with admin rights and/or on the installation folder (can't help more I'm not familiar at all with mac)
