### ISSUE TITLE
timestep limit for a single simulation

### ISSUE THREAD

**Issue by spMohanty** [stanfordnmbl/osim-rl#24]
The timestep limit for a particular simulation should be 500 (https://github.com/stanfordnmbl/osim-rl/blob/master/osim/env/osim.py#L70).

But while analysing the training logs to see the variation in path-lengths, I noticed there were quite a few simulations which run for more than 500 steps.
The reason being, I use the `done` response as the feedback for ending a simulation, and would expect it to end a simulation after 500 steps.

Is this an expected functionality ? or has it sneaked in by mistake ?
I think, the `is_done` (https://github.com/stanfordnmbl/osim-rl/blob/master/osim/env/run.py#L75) function should handle the upper bound on the max steps, at least for the grader.

**Comment by spMohanty** [comment]
With reference to the grader, I get this error if I try to reset the env after 500 steps (and the pelvis is still above the threshold)

```
[2017-06-23 02:38:52,828] Exception on /v1/envs/4f2b61e1aaf03d3283f135febbe225a4___1c549709df/reset/ [POST]
Traceback (most recent call last):
  File "/home/ubuntu/anaconda2/envs/opensim-rl/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/anaconda2/envs/opensim-rl/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/anaconda2/envs/opensim-rl/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/anaconda2/envs/opensim-rl/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/anaconda2/envs/opensim-rl/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "gym_http_server.py", line 367, in env_reset
    observation = envs.reset(instance_id)
  File "gym_http_server.py", line 138, in reset
    obs = env._reset(difficulty=2, seed=SEED_MAP[env.trial-1])
  File "gym_http_server.py", line 60, in _reset
    self._before_reset()
  File "/home/ubuntu/anaconda2/envs/opensim-rl/lib/python2.7/site-packages/gym/wrappers/monitoring.py", line 190, in _before_reset
    self.stats_recorder.before_reset()
  File "/home/ubuntu/anaconda2/envs/opensim-rl/lib/python2.7/site-packages/gym/monitoring/stats_recorder.py", line 68, in before_reset
    raise error.Error("Tried to reset environment which is not done. While the monitor is active for {}, you cannot call reset() unless the episode is over.".format(self.env_id))
Error: Tried to reset environment which is not done. While the monitor is active for 0, you cannot call reset() unless the episode is over.
```
