### ISSUE TITLE
Can't submit because of 405 from grader.crowdai.org:1729/v1/envs/

### ISSUE THREAD

**Issue by AdamStelmaszczyk** [stanfordnmbl/osim-rl#38]
With HEAD at 8572f34613f2ee842f259a3bdb69c6456575716f:

```
$ python submit.py --token XXX
Updating Model file from 30000 to latest format...
Loaded model gait9dof18musc_Thelen_BigSpheres.osim from file /home/adam/anaconda2/envs/opensim-rl/lib/python2.7/site-packages/osim/env/../models/gait9dof18musc.osim
[2017-07-13 20:09:06,334] POST http://grader.crowdai.org:1729/v1/envs/
{"env_id": "Run", "token": "688545d8ba985c174b4f967b40924a43"}
Traceback (most recent call last):
  File "submit.py", line 16, in <module>
    observation = client.env_create(args.token)
  File "/home/adam/anaconda2/envs/opensim-rl/lib/python2.7/site-packages/osim/http/client.py", line 52, in env_create
    resp = self._post_request(route, data)
  File "/home/adam/anaconda2/envs/opensim-rl/lib/python2.7/site-packages/osim/http/client.py", line 40, in _post_request
    return self._parse_server_error_or_raise_for_status(resp)
  File "/home/adam/anaconda2/envs/opensim-rl/lib/python2.7/site-packages/osim/http/client.py", line 31, in _parse_server_error_or_raise_for_status
    raise ServerError(message=j["message"], status_code=resp.status_code)
osim.http.client.ServerError
```

```
$ curl http://grader.crowdai.org:1729/v1/envs/
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>
```

**Comment by kidzik** [comment]
We are in progress of introducing changes from
https://github.com/stanfordnmbl/osim-rl/issues/31
there are now on the `master` branch. I'm writing a tutorial how to submit solutions trained before using the new observation vector or how to retrain with the new data in the observation. Sorry for the inconvenience.

**Comment by AdamStelmaszczyk** [comment]
No problem, thank you.

**Comment by kidzik** [comment]
I put the updates here https://github.com/stanfordnmbl/osim-rl/tree/master/docs please let me know if you experience any problems.
