### ISSUE TITLE
osim.http.client.ServerError on submission

### ISSUE THREAD

**Issue by parilo** [stanfordnmbl/osim-rl#40]
I'm using linux and get this on submission
it fails on client.env_create('my key')
`
Loaded model gait9dof18musc_Thelen_BigSpheres.osim from file /home/anton/anaconda3/envs/opensim-rl/lib/python2.7/site-packages/osim/env/../models/gait9dof18musc.osim
[2017-07-14 10:04:42,128] POST http://grader.crowdai.org:1729/v1/envs/
{"env_id": "Run", "token": "my key"}
Traceback (most recent call last):
  File "submit.py", line 24, in <module>
    observation = client.env_create('my key')
  File "/home/anton/anaconda3/envs/opensim-rl/lib/python2.7/site-packages/osim/http/client.py", line 52, in env_create
    resp = self._post_request(route, data)
  File "/home/anton/anaconda3/envs/opensim-rl/lib/python2.7/site-packages/osim/http/client.py", line 40, in _post_request
    return self._parse_server_error_or_raise_for_status(resp)
  File "/home/anton/anaconda3/envs/opensim-rl/lib/python2.7/site-packages/osim/http/client.py", line 31, in _parse_server_error_or_raise_for_status
    raise ServerError(message=j["message"], status_code=resp.status_code)
osim.http.client.ServerError
`
Please help to resolve this issue

**Comment by parilo** [comment]
updating by
`pip install git+https://github.com/stanfordnmbl/osim-rl.git`
solved the problem
