### ISSUE TITLE
Submission error: TypeError: Array is not JSON serializable

### ISSUE THREAD

**Issue by Faur** [stanfordnmbl/osim-rl#45]
I am having trouble submitting. I am on Windows 10, and have followed the setup in the README (`Python 2.7`, `opensim 4.0.0`, `osim-rl 1.4.1`). I have modified the basic script, to a minimal failing example:

```
import opensim as osim
from osim.http.client import Client
from osim.env import RunEnv

# Settings
remote_base = "http://grader.crowdai.org:1729"
crowdai_token = # something on the form: ec790...

client = Client(remote_base)

# Create environment
observation = client.env_create(crowdai_token)

# IMPLEMENTATION OF YOUR CONTROLLER
env = RunEnv(visualize=False)

while True:
    [observation, reward, done, info] = client.env_step(env.action_space.sample(), True)
    print(observation)
    if done:
        observation = client.env_reset()
        if not observation:
            break

client.submit()
```

I get the following output
```
[2017-08-08 11:58:49,009] POST http://grader.crowdai.org:1729/v1/envs/
{"env_id": "Run", "token": "ec790bd1915dc26cc3c164ff2a5c97fd", "version": "1.4.1"}
[2017-08-08 11:58:50,272] POST http://grader.crowdai.org:1729/v1/envs/ec790bd1915dc26cc3c164ff2a5c97fd___48b52647fc/monitor/start/
{"directory": "tmp", "video_callable": false, "force": true, "resume": false}
[2017-08-08 11:58:51,540] POST http://grader.crowdai.org:1729/v1/envs/ec790bd1915dc26cc3c164ff2a5c97fd___48b52647fc/reset/
null
Updating Model file from 30000 to latest format...
Loaded model gait9dof18musc_Thelen_BigSpheres.osim from file C:\Anaconda\envs\opensim-rl\lib\site-packages\osim\env\../models/gait9dof18musc.osim
Traceback (most recent call last):
  File "env_submit.py", line 55, in <module>
    [observation, reward, done, info] = client.env_step(env.action_space.sample(), True)
  File "C:\Anaconda\envs\opensim-rl\lib\site-packages\osim\http\client.py", line 72, in env_step
    resp = self._post_request(route, data)
  File "C:\Anaconda\envs\opensim-rl\lib\site-packages\osim\http\client.py", line 39, in _post_request
    logger.info("POST {}\n{}".format(url, json.dumps(data)))
  File "C:\Anaconda\envs\opensim-rl\lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Anaconda\envs\opensim-rl\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Anaconda\envs\opensim-rl\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Anaconda\envs\opensim-rl\lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: array([ 0.5488135 ,  0.71518937,  0.60276338,  0.54488318,  0.4236548 ,
        0.64589411,  0.43758721,  0.891773  ,  0.96366276,  0.38344152,
        0.79172504,  0.52889492,  0.56804456,  0.92559664,  0.07103606,
        0.0871293 ,  0.0202184 ,  0.83261985]) is not JSON serializable
```

**Comment by AdamStelmaszczyk** [comment]
`env.action_space.sample()` is a numpy array, which is not JSON serializable.

To debug and see this you could print (or `pdb`) suspicious variables from the pointed line `  File "env_submit.py", line 55, in <module>
    [observation, reward, done, info] = client.env_step(env.action_space.sample(), True)`.

I'd do [`env.action_space.sample().tolist()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.tolist.html), this will convert it to ordinary Python list, which is JSON serializable.

**Comment by Faur** [comment]
Thank you, this works.

**Comment by rafaelvalero** [comment]
Alternatively you could encode as[ in this post](https://stackoverflow.com/a/47809410/7127519)
