### ISSUE TITLE
Can't submit because of 404 Client Error: NOT FOUND for url: http://grader.crowdai.org:1729/v1/envs/

### ISSUE THREAD

**Issue by AdamStelmaszczyk** [stanfordnmbl/osim-rl#48]
```
adam@adam-ThinkPad-T520 ~/Desktop/running/stuff/osim-rl $ python scripts/submit.py --token XXX
Updating Model file from 30000 to latest format...
Loaded model gait9dof18musc_Thelen_BigSpheres.osim from file /home/adam/Desktop/running/stuff/osim-rl/osim/env/../models/gait9dof18musc.osim
[2017-08-11 14:18:24,879] POST http://grader.crowdai.org:1729/v1/envs/
{"env_id": "Run", "token": "688545d8ba985c174b4f967b40924a43", "version": "1.4.1"}
Traceback (most recent call last):
  File "scripts/submit.py", line 19, in <module>
    observation = client.env_create(args.token)
  File "/home/adam/Desktop/running/stuff/osim-rl/osim/http/client.py", line 57, in env_create
    resp = self._post_request(route, data)
  File "/home/adam/Desktop/running/stuff/osim-rl/osim/http/client.py", line 43, in _post_request
    return self._parse_server_error_or_raise_for_status(resp)
  File "/home/adam/Desktop/running/stuff/osim-rl/osim/http/client.py", line 34, in _parse_server_error_or_raise_for_status
    resp.raise_for_status()
  File "/home/adam/.local/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: NOT FOUND for url: http://grader.crowdai.org:1729/v1/envs/
```

**Comment by xueeinstein** [comment]
I also met this issue. Any fix now?

**Comment by AdamStelmaszczyk** [comment]
Works for me now, closing. If it still happens to you feel free to re-open.

https://www.crowdai.org/topics/judger-is-down/comments/new
