### ISSUE TITLE
Can't submit because of 500 Internal Server Error

### ISSUE THREAD

**Issue by AdamStelmaszczyk** [stanfordnmbl/osim-rl#68]
Usually it happens in the beginning, but sometimes later during a submit:

```
Updating Model file from 30000 to latest format...
Loaded model gait9dof18musc_Thelen_BigSpheres.osim from file /home/adam/Desktop/running/stuff/osim-rl/osim/env/../models/gait9dof18musc.osim
[2017-09-08 11:31:03,090] POST http://grader.crowdai.org:1729/v1/envs/
{"env_id": "Run", "token": "XXX", "version": "1.4.1"}
Traceback (most recent call last):
  File "scripts/submit.py", line 19, in <module>
    observation = client.env_create(args.token)
  File "/home/adam/Desktop/running/stuff/osim-rl/osim/http/client.py", line 56, in env_create
    resp = self._post_request(route, data)
  File "/home/adam/Desktop/running/stuff/osim-rl/osim/http/client.py", line 42, in _post_request
    return self._parse_server_error_or_raise_for_status(resp)
  File "/home/adam/Desktop/running/stuff/osim-rl/osim/http/client.py", line 31, in _parse_server_error_or_raise_for_status
    resp.raise_for_status()
  File "/home/adam/.local/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://grader.crowdai.org:1729/v1/envs/
```

To reproduce: `python scripts/submit.py --token XXX` from `osim-rl` root directory.

Or with `curl`:

```
$ curl -H "Content-Type: application/json" -d '{"env_id": "Run", "token": "XXX", "version": "1.4.1"}' -X POST http://grader.crowdai.org:1729/v1/envs/ 
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```

Looks like it affects everybody as hagrid67, mpavlov wrote about it [here](https://www.crowdai.org/topics/submission-problems-server-error/comments/new) and zzzgemini, ViktorM, blazej0 [here](https://gitter.im/crowdAI/NIPS-Learning-To-Run-Challenge).

**Comment by ctmakro** [comment]
same, except a 502 Bad Gateway. Seems the server was under maintenance

**Comment by kidzik** [comment]
@spMohanty can you please take a look into this problem?

**Comment by kidzik** [comment]
We've put more computational resources to the grader, should be better now!
