### ISSUE TITLE
Failed to start the visualizer(Internal error <FBConfig with necessary capabilities not found> in function fgOpenWindow)

### ISSUE THREAD

**Issue by wyixiang** [stanfordnmbl/osim-rl#74]
I'm trying to run a simple code, by connecting to a remote linux server. And I have done X11 forwarding, but I still fail to start the visualizer when "env = RunEnv(visualize=True)".
```
(opensim-rl) xuanyang@machine10:~$ python ./py2/testpy2.py
Updating Model file from 30000 to latest format...
Loaded model gait9dof18musc_Thelen_BigSpheres.osim from file /home/xuanyang/anaconda2/envs/opensim-rl/lib/python2.7/site-packages/osim/env/../models/gait9dof18musc.osim
freeglut (simbody-visualizer):  ERROR:  Internal error <FBConfig with necessary capabilities not found> in function fgOpenWindow
Traceback (most recent call last):
  File "./py2/testpy2.py", line 3, in <module>
    env = RunEnv(visualize=True)
  File "/home/xuanyang/anaconda2/envs/opensim-rl/lib/python2.7/site-packages/osim/env/run.py", line 43, in __init__
    manager.integrate(state)
  File "/home/xuanyang/anaconda2/envs/opensim-rl/lib/python2.7/site-packages/opensim/simulation.py", line 38364, in integrate
    return _simulation.Manager_integrate(self, *args)
RuntimeError: std::exception in 'bool OpenSim::Manager::integrate(SimTK::State &)': SimTK Exception thrown at VisualizerProtocol.cpp:378:
  Error detected by Simbody method VisualizerProtocol: An attempt to write() 1 bytes to pipe 4 failed with errno=32 (Broken pipe).
  (Required condition 'status!=-1' was not met.)
```

**Comment by kidzik** [comment]
It might be the same problem as here https://github.com/simbody/simbody/issues/550 (and https://github.com/simbody/simbody/issues/563), which are not resolved yet. Normally it is enough to restart the script. We had a similar problem with generating a video. @spMohanty, do you have some solution here?

**Comment by spMohanty** [comment]
Yeah, this looks like the same issue.
The only makeshift fix we have for now, is to both restart the environment, and the script.
Just restarting the script also keeps throwing the same broken pipe error.
Ugly, true, but thats the only working solution we have for now 😢
